### ISSUE TITLE
Issues build on macOS / Ruby 2.6

### ISSUE THREAD

**Issue by kirs** [digital-fabric/polyphony#20]
On the current master branch, macOS 10.15.5, ruby 2.6.5p114.

```
...
6 warnings generated.
compiling libev_queue.c
compiling polyphony.c
compiling polyphony_ext.c
compiling socket.c
socket.c:155:14: warning: unused function 'Socket_accept' [-Wunused-function]
static VALUE Socket_accept(VALUE sock) {
             ^
1 warning generated.
compiling thread.c
compiling tracing.c
linking shared-object polyphony_ext.bundle
duplicate symbol '_ID_empty' in:
    polyphony.o
    thread.o
duplicate symbol '_ID_pop' in:
    polyphony.o
    thread.o
duplicate symbol '_ID_push' in:
    polyphony.o
    thread.o
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [polyphony_ext.bundle] Error 1
```

Any idea what could be wrong?

**Comment by ciconia** [comment]
Hi, I just pushed version 0.43.1 which should fix this issue. Please try again and let me know if it works.

**Comment by kirs** [comment]
Thanks, I can confirm it fixes it!
